12/avoid rest
jnduli/pomodoro pull request #13
Opened 2020-01-06 06:45 UTC by jnduli

Closss issue #12

2020-01-06 08:27 UTC, BonfaceKilz requested changes
I've run `shellcheck` and everything is ok. Other than that, check out the comments above.

2020-01-06 08:27 UTC, BonfaceKilz commented on pomodoro.sh
> +    # $3 is n time it has looped spent (for continue support)
This comment is not clear

2020-01-06 08:27 UTC, BonfaceKilz commented on pomodoro.sh
> +    echo "Press c to continue with task"
I'd recommend using heredocs like this:
```
cat <<EOF
Press q to stop chiming, and start break
Press c to continue with task

EOF
```

2020-01-06 08:27 UTC, BonfaceKilz commented on pomodoro.sh
> +        if [[ $input = "q" || $input = "Q" ]]; then
NIT:
```suggestion
        if [[ ${input^^} = "Q" ]]; then
```
`${input^^}`: the 2 carats capitalizes the variable

2020-01-06 08:27 UTC, BonfaceKilz commented on pomodoro.sh
> +        if [[ $input = "c" || $input = "C" ]]; then
Same as above.

2020-01-06 08:28 UTC, BonfaceKilz commented
Also check this out: https://google.github.io/styleguide/shell.xml

2020-01-07 06:19 UTC, jnduli commented
I've fixed  the above raised issues. Thanks for the suggestions.

2020-01-07 07:00 UTC, BonfaceKilz approved these changes
LGTM other than the minor nitpick on `echo ""` that I've pointed at above.

2020-01-07 07:00 UTC, BonfaceKilz commented on pomodoro.sh
>      echo ""
NIT: Since we are user heredocs with don't need this empty echo

2020-01-07 07:57 UTC, merged