Replace wc with tail + bash arrays
jnduli/pomodoro pull request #26
Opened 2020-01-24 09:43 UTC by jnduli

Closes #23

Replaces `wc` with `tail` which is more widely used I think.

2020-01-24 12:43 UTC, BonfaceKilz commented on pomodoro.sh
> +        arr=($(tail -1 $LOG_FILENAME))
You should add a comment to describe what this does because it looks cryptic

2020-01-24 12:46 UTC, BonfaceKilz requested changes
`wc` in as much is a dependency is pretty obvious in what it does. When you replace it with bash built-ins, I propose you add a comment since said built-ins can be hard to read

2020-01-24 13:23 UTC, jnduli commented
Noted. Just added the comment explanation.

On 20/01/24 04:46AM, BonfaceKilz wrote:
> BonfaceKilz requested changes on this pull request.
> 
> `wc` in as much is a dependency is pretty obvious in what it does. When you replace it with bash built-ins, I propose you add a comment since said built-ins can be hard to read
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jnduli/pomodoro/pull/26#pullrequestreview-347930437

2020-01-26 10:19 UTC, BonfaceKilz approved these changes
LGTM

2020-01-30 10:10 UTC, merged